extends: default

rules:
  document-start: disable
  line-length:
    max: 120
  truthy:
    check-keys: false
  indentation:
    spaces: 2
    indent-sequences: whatever
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  empty-lines: disable
